"""empty message

Revision ID: dff50e50863a
Revises: dbfd9458be7a
Create Date: 2025-02-09 03:23:55.127099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff50e50863a'
down_revision = 'dbfd9458be7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
